cache_length: 600
debug: true
timeout: 10
user_agent: Package Control Default Channel Server
http_cache: true
install_prereleases: true
downloader_precedence: 
    windows: [wininet, oscrypto]
    osx: [oscrypto, urllib, curl]
    linux: [oscrypto, urllib, curl, wget]
query_string_params:
    api.github.com:
        client_id: "Use config.read_secret('github_client_id')"
        client_secret: "Use config.read_secret('github_client_secret')"
